export interface Medical{


  pregnancy:String,
  typeOfDelivery:String,
  alcohol: Boolean,
  smoking: Boolean,
  medications : String,
  pregnancyComplications: String,
  pregnancyType :String,
  prematureMonths: String,
  babyCry: String,
  feedingProblem: String,
  sleepProblem: String,
  birthWeight: String,
  birthCompilcation: String,
  importantIllness : String,
  medicalCondition :String,
  consanguineousMarriageHistory : String,
  history : String,
  remarksVision : String,
  eyeTest : Boolean,
  useGlass : Boolean,
  eyeProblem : Boolean,
  remarksHearing : String,
  hearingTest : Boolean,
  hearingAid : Boolean,
  earProblem : Boolean,
  currentMedication :String,
  previoustMedication : String,
  allergies : String,
  actualTherapies:String,
  previousTherapies : String,
  headRaise : String,
  rollOver : String,
  independentSitting :String,
  crawled : String,
  pulledToStand : String,
  independentStanding : String,
  walking : String,
  dress:String,
  spoon : String,
  saidFirstWords:String,
  babbling : String,
  presentLanguage : String,
  fingerFeeding :String,
  cloudinary_id :String,
  file_url :String,

}
