export interface Routine{
  feedAge:String,
  goodAppetitie:String,
  messyEater:String,
  foodPreference:String,
  tasteAndTexture:String,
  ageAppropriate:String,
  canDoUpButtons:String,
  canPutOnSocks:String,
  canPutOnShoes:String,
  toiletTrained:String,
  dayAndNight:String,
  toiletNight: String,
  toiletRemarks: String,
  // toiletingAndBath :String,
  // toiletiTrained:String,
  accidents:String,
  toiletPaperUse:String,
  managingClothing:String,
  washingHands:String,
  bathingAndBrushing:String,
  typicalNightSleep:String,
  timeOfSleep:String,
  remarksSleep:String,
  typicalWakeup:String,
  timeOfWakeup:String,
  remarksWakeUp:String,
  homework:String,
  remarksHomework:String,
  // externalSupports:String,
  routineStrategies:String,
  difficultSituation:String,
  remarksChildBehaviour:String,
  movementBreaks:String,
  howYouKnowAboutUs:String,
}


