import { SessionMaster } from "./sessionMaster"

export  interface BtSessionData{
  _id: String,
  date: Date,
  updatedDate: Date,
  session_master_id: SessionMaster,
  sitting : String,
  remarksSitting : String,
  eyeContact : String,
  remarksEyeContact : String,
  attention : String,
  remarksAttention : String,
  mood : String,
  remarksMood : String,
  activities : String,
  remarksActivities : String,
  comprehensionInstructions : String,
  remarksComprehensionInstructions : String,
  responseInstructions : String,
  remarksResponseInstructions : String,
  waiting : String,
  remarksWaiting : String,
  compliance : String,
  remarksCompliance : String,
  behaviour : String,
  remarksBehaviour : String,
  communication : String,
  remarksCommunication : String,

  throwThings : String,
  remarksThrowThings : String,
  tearsThings : String,
  remarksTearsThings : String,
  angryProne : String,
  remarksAngryProne : String,
  selfInjurious : String,
  remarksSelfInjurious : String,
  repetitive : String,
  remarksRepetitive : String,
  tantrums : String,
  remarksTantrums : String,
  climbsFurniture : String,
  remarksClimbsFurniture : String,
  disruptiveBehaviour : String,
  remarksDisruptiveBehaviour : String
}
